import vine, { SimpleMessagesProvider } from '@vinejs/vine'

vine.messagesProvider = new SimpleMessagesProvider({  
  "above": "O campo {{field}} deve estar acima de {{argument.0}}.",
  "accepted": "O campo {{field}} deveria ter sido aceito",
  "after": "O campo {{field}} deve ser uma data após {{argument.0}}",
  "after_offset_of": "O campo {{field}} deve ser depois de {{argument.0}} {{argument.1}} da data de hoje",
  "alpha": "O campo {{field}} deve conter apenas letras",
  "alpha_numeric": "O campo {{field}} deve conter apenas letrase números",
  "array": "O campo {{field}} deve ser um ARRAY.",
  "before": "O campo {{field}} deve ser uma dataantes de {{argument.0}}.",
  "before_offset_of": "O campo {{field}} deve estar antes de {{argument.0}} {{argument.1}} da data de hoje",
  "between": "O campo {{field}} deve estar entre {{argument.0}} e {{argument.1}}.",
  "boolean": "O {{campo}} deve ser verdadeiro ou falso.",
  "confirmed": "A confirmação do campo {{field}} não corresponde.",
  "date": "O campo {{field}} deve ser uma data válida",
  "date_format": "O campo {{field}} deve ser uma data válida de acordo com o formato dado {{argument.0}}.",
  "different": "O campo {{field}} e o {{argument.0}} devem ser diferentes.",
  "email": "Digite um email válido.",
  "ends_with": "O campo {{field}} deve terminar com determinadas letras ({{argument}}).",
  "equals": "O campo {{field}} deve ser igual a {{argument.0}}.",
  "in": "O campo {{field}}deve estar dentro dos valores definidos de ({{argument}}).",
  "includes": "O campo {{field}} deve incluir letras de definição ({{argument}}).",
  "integer": "O campo {{field}} deve ser um INTEGER.",
  "ip": "O campo {{field}} deve ser um endereço IP válido.",
  "ipv4": "O campo {{field}} deve ser um endereço IPV4válido.",
  "ipv6": "O campo {{field}} deve ser um endereço IPV6 válido.",
  "json": "O campo {{field}} deve ser uma string JSON válida.",
  "max": "O campo {{field}} não deve ser maior que {{argument.0}}.",
  "min": "O campo {{field}} não deve ser menor que {{argument.0}}.",
  "not_equals": "O campo {{field}} deve ser diferente de {{argument.0}}.",
  "not_in": "O campo {{field}} não deve ser um dos ({{argument}}).",
  "object": "O {{field}} deve ser um OBJETO válido.",
  "range": "O campo {{field}} deve estar entre {{argument.0}} e {{argument.1}}.",
  "regex": "O formato do campo {{field}} é inválido.",
  "required": "O campo {{field}} é obrigatório.",
  "required_if": "O campo {{field}} é necessário quando {{argument.0}} existir.",
  "required_when": "O campo {{field}} é necessário quando o valor de {{argument.0}} é igual a {{argument.1}}",
  "required_with_all": "O campo {{field}} é necessário quando todos os ({{argument}}) estão presentes.",
  "required_with_any": "O campo {{field}} é requerido quando algum de ({{argument}}) está presente.",
  "required_without_all": "O campo {{field}} é necessário quando nenhum dos ({{argument}}) está presente.",
  "required_without_any": "O campo {{field}} é requerido quando algum de ({{argument}}) está presente.",
  "same": "{{field}} e {{argument.0}} devem corresponder.",
  "starts_with": "O campo {{field}} deve começar com determinadas letras ({{argument}}).",
  "string": "O campo {{field}} deve ser um STRING.",
  "under": "O campo {{field}} deve estar em {{argument.0}}.",
  "unique": "O campo {{field}} já foi usado por outra pessoa.",
  "url": "O campo {{field}} deve ser um URL válido.",


  "birthday.date": "Formato de data inválido.",

  "password.confirmed": "A confirmação de senha não confere.",

  "birthday.date.beforeOrEqual": "Usuário deve ter no mínimo 12 anos.",

  "email.database.unique": "Email já cadastrado no sistema.",

  "name.required": "O campo nome é obrigatório.",
  "nickname.required": "O campo apelido é obrigatório.",
  "email.required": "O campo email é obrigatório.",
  "email.database.exists": "O campo email é obrigatório.",
  "birthday.required": "O campo data de nascimento é obrigatório.",
  "password.required": "O campo senha é obrigatório.",
  "password_confirmation.required": "O campo confirmação de senha é obrigatório.",
  "code.required": "O código de verificação é obrigatório.",
  "code.number": "Código inválido.",
})
